language: go
install:
- go get -v github.com/spf13/hugo
- npm install -g bower
- bower install
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: f4MYx5j9tmmIPNDT5kE5lwFp+YWixXLvCBoAQeSqJftN66R1tvclIZ4Oe4tB2N2FN7lCscMsbcdpfwnS7SeDhjLPbfkyOwywtcEqALmhoKS17hOjN+UBxIM1koQXx9ZGrHHLlcKMtlE4KjnOWoTFmEvDVWs0dMj7NMkeFkydGYa/z0ee46pc8d7ls0CYSx3vbWIt15Klzta2d415siB+I1N+1WNvvddhKznTqEezmM63J2mUgblSgUMlxE6dLBrYvE6g5Msk9kbt+Zf9dd3gPf1h3OOHX0OcRe/ktgz1fx1f2mIn5Q2nsF1ZKofYLqvZHNPCTuPM8blXHwKqQYqHBzpHkL+WrPyd0jgX7wbBbv1xAHmOZFJPA1Povw/IMazMHQmVdXvprKvtIiFjBvA/ww51Vzpa2X8hV+gfxYcBfZMqwdJ++lqhEpP5ovCg9Q+r+GKLdchXszvf1DbzBAN3mi9gZ1dHA8/Q5qpj9SGhYE5XVLxmDmgC7x3M+Y2dTAwMJs/U/XNv6XPn9AeErrLuEmD6IdgvloONZbUKmepuAkn3+lYwt6Mc0Djh9C+NLQl5SnRVmTVRThCAsx4Wy5o7ADR9XQ02x8i28lh+nz47EG1wqCNxwb6OiZ/CrNyCbkzzeMve1palIRhx8RrqxPf69svxYgQnnXZgYoLSgUmNfXo=
  - secure: DlN7XYbI7pviHZtclNqG4ldUNWsiU9GHrubiIFI1YH1V8PfjsAUUPSsVs5/GNLQU+QtDmmrD4Qj1PGXLR/VqMRc7kIsrWoN8sQI3n2N6MLG9fAUy/x6ZrU2Zu3QG0jLcE1TPmIEmibcX35N/eQqFNQqqaS+sRfg6ksKJ0O1B84ijYbaTNZVrmP5x2hQ4gYoX1Aybvg3HAT1O0zEmdGnK1SW3eaUDsOvXTOzqukukeFmXgcw3jD++Jmll6hJqc0Wk36Oxv3OV7ALEbBYzZXbO6OgYQM5pWqyO50ngrQSP9BoswjFife/T8TSaNb4FHRsoD/bCNsqqPRbLhmiMCV5k9W4+oMFxCGNznivQigtbdqdg7odgnDJHNYVVX60kZxDoBSozes/8pVBFFuXx2r9SRt5X36IJIdH3BKrMP/0cXnyt+t8e6K1z2WJy4sfU8ap/bBQ8vDC/o2/OosmC7qe/dqczP0+BZF5rebzye8qO0hWmKbDddi/bnDc2HuoLjfZyEK4FzIp8LXJFXg6ehfaLBfUMLJ/jJZnwdYybDmcWmNiJXnI2IgVl8mu9W8jN7JD3XdxakCIAl+oCC+oqbKx8KEjN/dz7m/rUD6KWChD99KZgwKVoWR7pXIuzPplo6LaOuPWBGikP84Jwf549yeW6IGt6gcYT+5VVuOxII6cVNdk=
